{'01/13': {'6:00 Court 6': [['Bill', 'Brian', 'Jacek', 'Nick']],
           '7:30 Court 6': [['Brad', 'Dan', 'Kumar', 'Trung']],
           'off': ['Jeff R', 'Murali', 'Steve'],
           'requested_off': ['Murali']},
 '01/20': {'6:00 Court 6': [['Brad', 'Jacek', 'Murali', 'Steve']],
           '7:30 Court 6': [['Dan', 'Jeff R', 'Nick', 'Trung']],
           'off': ['Brian', 'Kumar', 'Bill'],
           'requested_off': ['Brian']},
 '01/27': {'6:00 Court 6': [['Jeff R', 'Kumar', 'Murali', 'Steve']],
           '7:30 Court 6': [['Bill', 'Dan', 'Jacek', 'Nick']],
           'off': ['Brad', 'Brian', 'Trung'],
           'requested_off': ['Brian']},
 '02/03': {'6:00 Court 6': [['Brian', 'Jeff R', 'Kumar', 'Murali']],
           '7:30 Court 6': [['Bill', 'Brad', 'Steve', 'Trung']],
           'off': ['Dan', 'Jacek', 'Nick'],
           'requested_off': []},
 '02/10': {'6:00 Court 6': [['Bill', 'Brad', 'Brian', 'Jeff R']],
           '7:30 Court 6': [['Dan', 'Kumar', 'Nick', 'Steve']],
           'off': ['Jacek', 'Murali', 'Trung'],
           'requested_off': ['Murali']},
 '02/17': {'6:00 Court 6': [['Brad', 'Jacek', 'Murali', 'Trung']],
           '7:30 Court 6': [['Bill', 'Jeff R', 'Kumar', 'Steve']],
           'off': ['Brian', 'Dan', 'Nick'],
           'requested_off': []},
 '02/24': {'6:00 Court 6': [['Brad', 'Brian', 'Jacek', 'Murali']],
           '7:30 Court 6': [['Dan', 'Jeff R', 'Nick', 'Trung']],
           'off': ['Kumar', 'Steve', 'Bill'],
           'requested_off': []},
 '03/03': {'6:00 Court 6': [['Brian', 'Dan', 'Murali', 'Steve']],
           '7:30 Court 6': [['Jacek', 'Kumar', 'Nick', 'Trung']],
           'off': ['Brad', 'Jeff R', 'Bill'],
           'requested_off': []},
 '03/10': {'6:00 Court 6': [['Bill', 'Brad', 'Murali', 'Trung']],
           '7:30 Court 6': [['Brian', 'Jacek', 'Jeff R', 'Kumar']],
           'off': ['Dan', 'Nick', 'Steve'],
           'requested_off': []},
 '03/17': {'6:00 Court 6': [['Bill', 'Brad', 'Murali', 'Nick']],
           '7:30 Court 6': [['Brian', 'Dan', 'Steve', 'Trung']],
           'off': ['Jacek', 'Jeff R', 'Kumar'],
           'requested_off': []},
 '03/31': {'6:00 Court 6': [['Brad', 'Brian', 'Jacek', 'Nick']],
           '7:30 Court 6': [['Dan', 'Jeff R', 'Kumar', 'Steve']],
           'off': ['Murali', 'Trung', 'Bill'],
           'requested_off': []},
 '04/07': {'6:00 Court 6': [['Bill', 'Dan', 'Murali', 'Nick']],
           '7:30 Court 6': [['Brian', 'Jeff R', 'Steve', 'Trung']],
           'off': ['Brad', 'Jacek', 'Kumar'],
           'requested_off': []},
 '04/14': {'6:00 Court 6': [['Bill', 'Brad', 'Brian', 'Kumar']],
           '7:30 Court 6': [['Jacek', 'Jeff R', 'Murali', 'Nick']],
           'off': ['Dan', 'Steve', 'Trung'],
           'requested_off': []},
 '04/21': {'6:00 Court 6': [['Kumar', 'Murali', 'Nick', 'Trung']],
           '7:30 Court 6': [['Bill', 'Brian', 'Jacek', 'Steve']],
           'off': ['Brad', 'Dan', 'Jeff R'],
           'requested_off': []},
 '04/28': {'6:00 Court 6': [['Brad', 'Dan', 'Jeff R', 'Murali']],
           '7:30 Court 6': [['Bill', 'Brian', 'Nick', 'Steve']],
           'off': ['Jacek', 'Kumar', 'Trung'],
           'requested_off': []},
 '05/05': {'6:00 Court 6': [['Brad', 'Dan', 'Kumar', 'Trung']],
           '7:30 Court 6': [['Bill', 'Jacek', 'Jeff R', 'Steve']],
           'off': ['Brian', 'Murali', 'Nick'],
           'requested_off': []}}
