[['09/18','Court 4', ('Dan Gass', None), ('Matt Huth', None)],
 ['09/18','Court 5', ('Brian Berner', 9), ('Trevor Holwell', 7)],
 ['09/18','Court 6', ('Dan DeMuro', 9), ('Eric Groncki', 4)],
 ['09/18', 'off', 'Amit Taneja, Bryan Ersoy'],
 ['09/25','Court 3', ('Amit Taneja', None), ('Bryan Ersoy', None)],
 ['09/25','Court 4', ('Eric Groncki', None), ('Trevor Holwell', None)],
 ['09/25','Court 5', ('Brian Berner', None), ('Matt Huth', None)],
 ['09/25', 'off', 'Dan DeMuro, Dan Gass'],
 ['10/02','Court 4', ('Bryan Ersoy', None), ('Matt Huth', None)],
 ['10/02','Court 5', ('Amit Taneja', None), ('Dan DeMuro', None)],
 ['10/02','Court 6', ('Brian Berner', None), ('Dan Gass', None)],
 ['10/02', 'off', 'Eric Groncki, Trevor Holwell'],
 ['10/09','Court 4', ('Dan DeMuro', None), ('Dan Gass', None)],
 ['10/09','Court 5', ('Amit Taneja', None), ('Eric Groncki', None)],
 ['10/09','Court 6', ('Matt Huth', None), ('Trevor Holwell', None)],
 ['10/09', 'off', 'Brian Berner, Bryan Ersoy'],
 ['10/16','Court 4', ('Dan Gass', None), ('Trevor Holwell', None)],
 ['10/16','Court 5', ('Bryan Ersoy', None), ('Eric Groncki', None)],
 ['10/16','Court 6', ('Amit Taneja', None), ('Brian Berner', None)],
 ['10/16', 'off', 'Dan DeMuro, Matt Huth'],
 ['10/23','Court 4', ('Bryan Ersoy', None), ('Dan DeMuro', None)],
 ['10/23','Court 5', ('Amit Taneja', None), ('Matt Huth', None)],
 ['10/23','Court 6', ('Dan Gass', None), ('Eric Groncki', None)],
 ['10/23', 'off', 'Brian Berner, Trevor Holwell'],
 ['10/30','Court 3', ('Brian Berner', None), ('Bryan Ersoy', None)],
 ['10/30','Court 4', ('Dan DeMuro', None), ('Trevor Holwell', None)],
 ['10/30','Court 5', ('Eric Groncki', None), ('Matt Huth', None)],
 ['10/30','Court 6', ('Amit Taneja', None), ('Dan Gass', None)],
 ['10/30', 'off', ''],
 ['11/06','Court 3', ('Amit Taneja', None), ('Trevor Holwell', None)],
 ['11/06','Court 4', ('Brian Berner', None), ('Dan DeMuro', None)],
 ['11/06','Court 5', ('Bryan Ersoy', None), ('Dan Gass', None)],
 ['11/06','Court 6', ('Eric Groncki', None), ('Matt Huth', None)],
 ['11/06', 'off', ''],
 ['11/13','Court 4', ('Dan DeMuro', None), ('Matt Huth', None)],
 ['11/13','Court 5', ('Brian Berner', None), ('Eric Groncki', None)],
 ['11/13','Court 6', ('Bryan Ersoy', None), ('Trevor Holwell', None)],
 ['11/13', 'off', 'Amit Taneja, Dan Gass'],
 ['11/20','Court 4', ('Dan Gass', None), ('Trevor Holwell', None)],
 ['11/20','Court 5', ('Brian Berner', None), ('Bryan Ersoy', None)],
 ['11/20','Court 6', ('Amit Taneja', None), ('Dan DeMuro', None)],
 ['11/20', 'off', 'Eric Groncki, Matt Huth'],
 ['12/04','Court 3', ('Brian Berner', None), ('Dan DeMuro', None)],
 ['12/04','Court 4', ('Dan Gass', None), ('Eric Groncki', None)],
 ['12/04','Court 5', ('Matt Huth', None), ('Trevor Holwell', None)],
 ['12/04','Court 6', ('Amit Taneja', None), ('Bryan Ersoy', None)],
 ['12/04', 'off', ''],
 ['12/11','Court 3', ('Bryan Ersoy', None), ('Dan Gass', None)],
 ['12/11','Court 4', ('Amit Taneja', None), ('Matt Huth', None)],
 ['12/11','Court 5', ('Dan DeMuro', None), ('Eric Groncki', None)],
 ['12/11','Court 6', ('Brian Berner', None), ('Trevor Holwell', None)],
 ]
