{'01/07': {'Court 4': [['Eric', 'Matt'], [None, None, True]],
           'Court 5': [['Jason', 'Zac'], [None, None, True]],
           'Court 6': [['Bejoy', 'Rob'], [None, None, True]],
           'off': ['Fanfu', 'James'],
           'requested_off': ['James']},
 '01/14': {'Court 4': [['Fanfu', 'James'], [None, None, True]],
           'Court 5': [['Eric', 'Zac'], [None, None, True]],
           'Court 6': [['Bejoy', 'Matt'], [None, None, True]],
           'off': ['Jason', 'Rob'],
           'requested_off': []},
 '01/21': {'Court 4': [['James', 'Rob'], [None, None, True]],
           'Court 5': [['Fanfu', 'Jason'], [None, None, True]],
           'Court 6': [['Eric', 'Zac'], [None, None, True]],
           'off': ['Bejoy', 'Matt'],
           'requested_off': ['Bejoy']},
 '01/28': {'Court 4': [['Jason', 'Matt'], [None, None, True]],
           'Court 5': [['Fanfu', 'Rob'], [None, None, True]],
           'Court 6': [['James', 'Zac'], [None, None, True]],
           'off': ['Bejoy', 'Eric'],
           'requested_off': ['Bejoy']},
 '02/04': {'Court 4': [['Bejoy', 'Jason'], [None, None, True]],
           'Court 5': [['Eric', 'Rob'], [None, None, True]],
           'Court 6': [['Fanfu', 'Matt'], [None, None, True]],
           'off': ['James', 'Zac'],
           'requested_off': []},
 '02/11': {'Court 4': [['James', 'Matt'], [None, None, True]],
           'Court 5': [['Eric', 'Fanfu'], [None, None, True]],
           'Court 6': [['Jason', 'Zac'], [None, None, True]],
           'off': ['Bejoy', 'Rob'],
           'requested_off': []},
 '02/18': {'Court 4': [['Eric', 'James'], [None, None, True]],
           'Court 5': [['Bejoy', 'Zac'], [None, None, True]],
           'Court 6': [['Matt', 'Rob'], [None, None, True]],
           'off': ['Fanfu', 'Jason'],
           'requested_off': []},
 '02/25': {'Court 4': [['James', 'Jason'], [None, None, True]],
           'Court 5': [['Bejoy', 'Eric'], [None, None, True]],
           'Court 6': [['Matt', 'Rob'], [None, None, True]],
           'off': ['Fanfu', 'Zac'],
           'requested_off': []},
 '03/04': {'Court 4': [['Eric', 'Jason'], [None, None, True]],
           'Court 5': [['Bejoy', 'Fanfu'], [None, None, True]],
           'Court 6': [['Rob', 'Zac'], [None, None, True]],
           'off': ['James', 'Matt'],
           'requested_off': []},
 '03/11': {'Court 4': [['Eric', 'James'], [None, None, True]],
           'Court 5': [['Jason', 'Rob'], [None, None, True]],
           'Court 6': [['Fanfu', 'Zac'], [None, None, True]],
           'off': ['Bejoy', 'Matt'],
           'requested_off': []},
 '03/18': {'Court 4': [['Bejoy', 'James'], [None, None, True]],
           'Court 5': [['Matt', 'Zac'], [None, None, True]],
           'Court 6': [['Fanfu', 'Jason'], [None, None, True]],
           'off': ['Eric', 'Rob'],
           'requested_off': ['Eric', 'Rob']},
 '03/25': {'Court 4': [['Bejoy', 'Matt'], [None, None, True]],
           'Court 5': [['James', 'Jason'], [None, None, True]],
           'Court 6': [['Fanfu', 'Zac'], [None, None, True]],
           'off': ['Eric', 'Rob'],
           'requested_off': ['Eric', 'Rob']},
 '04/08': {'Court 4': [['James', 'Rob'], [None, None, True]],
           'Court 5': [['Jason', 'Matt'], [None, None, True]],
           'Court 6': [['Bejoy', 'Zac'], [None, None, True]],
           'off': ['Eric', 'Fanfu'],
           'requested_off': ['Eric']},
 '04/15': {'Court 4': [['Eric', 'Rob'], [None, None, True]],
           'Court 5': [['James', 'Matt'], [None, None, True]],
           'Court 6': [['Bejoy', 'Fanfu'], [None, None, True]],
           'off': ['Jason', 'Zac'],
           'requested_off': []},
 '04/22': {'Court 4': [['Rob', 'Zac'], [None, None, True]],
           'Court 5': [['Bejoy', 'Eric'], [None, None, True]],
           'Court 6': [['Fanfu', 'James'], [None, None, True]],
           'off': ['Jason', 'Matt'],
           'requested_off': []}}
