{'01/07': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': ["James"]},
 '01/14': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '01/21': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': ["Bejoy"]},
 '01/28': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': ["Bejoy"]},
 '02/04': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '02/11': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '02/18': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '02/25': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '03/04': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '03/11': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '03/18': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': ["Rob"]},
 '03/25': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': ["Rob"]},
 '04/08': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '04/15': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '04/22': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []}           
}
