{'01/15': {'Court 4': [['Amit', 'Trevor'], [None, None, True]],
           'Court 5': [['Matt', 'Nick'], [None, None, True]],
           'Court 6': [['Eric', 'Rob'], [None, None, True]],
           'off': ['Brian', 'Dan'],
           'requested_off': ['Dan']},
 '01/22': {'Court 4': [['Nick', 'Eric'], [None, None, True]],
           'Court 5': [['Amit', 'Rob'], [None, None, True]],
           'Court 6': [['Trevor', 'Matt'], [None, None, True]],
           'off': ['Brian', 'Dan'],
           'requested_off': ['Brian', 'Dan']},
 '01/29': {'Court 4': [['Dan', 'Brian'], [None, None, True]],
           'Court 5': [['Eric', 'Matt'], [None, None, True]],
           'Court 6': [['Rob', 'Nick'], [None, None, True]],
           'off': ['Amit', 'Trevor'],
           'requested_off': []},
 '02/05': {'Court 4': [['Dan', 'Amit'], [None, None, True]],
           'Court 5': [['Brian', 'Trevor'], [None, None, True]],
           'Court 6': [['Nick', 'Matt'], [None, None, True]],
           'off': ['Eric', 'Rob'],
           'requested_off': []},
 '02/12': {'Court 4': [['Matt', 'Rob'], [None, None, True]],
           'Court 5': [['Dan', 'Eric'], [None, None, True]],
           'Court 6': [['Amit', 'Nick'], [None, None, True]],
           'off': ['Brian', 'Trevor'],
           'requested_off': []},
 '02/19': {'Court 4': [['Dan', 'Trevor'], [None, None, True]],
           'Court 5': [['Brian', 'Eric'], [None, None, True]],
           'Court 6': [['Matt', 'Rob'], [None, None, True]],
           'off': ['Amit', 'Nick'],
           'requested_off': []},
 '02/26': {'Court 4': [['Brian', 'Amit'], [None, None, True]],
           'Court 5': [['Trevor', 'Nick'], [None, None, True]],
           'Court 6': [['Dan', 'Matt'], [None, None, True]],
           'off': ['Eric', 'Rob'],
           'requested_off': []},
 '03/05': {'Court 4': [['Brian', 'Rob'], [None, None, True]],
           'Court 5': [['Amit', 'Eric'], [None, None, True]],
           'Court 6': [['Dan', 'Matt'], [None, None, True]],
           'off': ['Nick', 'Trevor'],
           'requested_off': []},
 '03/12': {'Court 4': [['Eric', 'Trevor'], [None, None, True]],
           'Court 5': [['Brian', 'Nick'], [None, None, True]],
           'Court 6': [['Rob', 'Amit'], [None, None, True]],
           'off': ['Dan', 'Matt'],
           'requested_off': []},
 '03/19': {'Court 4': [['Trevor', 'Rob'], [None, None, True]],
           'Court 5': [['Amit', 'Matt'], [None, None, True]],
           'Court 6': [['Dan', 'Nick'], [None, None, True]],
           'off': ['Brian', 'Eric'],
           'requested_off': []},
 '04/02': {'Court 4': [['Dan', 'Trevor'], [None, None, True]],
           'Court 5': [['Eric', 'Brian'], [None, None, True]],
           'Court 6': [['Nick', 'Rob'], [None, None, True]],
           'off': ['Amit', 'Matt'],
           'requested_off': []},
 '04/09': {'Court 4': [['Trevor', 'Amit'], [None, None, True]],
           'Court 5': [['Brian', 'Dan'], [None, None, True]],
           'Court 6': [['Eric', 'Matt'], [None, None, True]],
           'off': ['Nick', 'Rob'],
           'requested_off': []},
 '04/16': {'Court 4': [['Matt', 'Brian'], [None, None, True]],
           'Court 5': [['Nick', 'Eric'], [None, None, True]],
           'Court 6': [['Rob', 'Trevor'], [None, None, True]],
           'off': ['Amit', 'Dan'],
           'requested_off': []},
 '04/23': {'Court 4': [['Amit', 'Dan'], [None, None, True]],
           'Court 5': [['Brian', 'Nick'], [None, None, True]],
           'Court 6': [['Matt', 'Trevor'], [None, None, True]],
           'off': ['Eric', 'Rob'],
           'requested_off': []},
 '04/30': {'Court 4': [['Eric', 'Rob'], [None, None, True]],
           'Court 5': [['Amit', 'Brian'], [None, None, True]],
           'Court 6': [['Dan', 'Nick'], [None, None, True]],
           'off': ['Matt', 'Trevor'],
           'requested_off': []},
 '05/07': {'Court 4': [['Amit', 'Eric'], [None, None, True]],
           'Court 5': [['Rob', 'Dan'], [None, None, True]],
           'Court 6': [['Trevor', 'Brian'], [None, None, True]],
           'off': ['Matt', 'Nick'],
           'requested_off': []}}
