[['09/18',"Court 1", ('Randy Lee', 9), ('Samer Alanani', 4)],
 ['09/18', 'off', 'Jason Klein, Jason Visner, Nhan Vu, Nick Waring'],
 ['09/25',"Court 1", ('Jason Klein', None), ('Nhan Vu', None)],
 ['09/25',"Court 2", ('Jason Visner', None), ('Nick Waring', None)],
 ['09/25', 'off', 'Randy Lee, Samer Alanani'],
 ['10/02',"Court 1", ('Nhan Vu', None), ('Nick Waring', None)],
 ['10/02',"Court 2", ('Jason Klein', None), ('Jason Visner', None)],
 ['10/02',"Court 3", ('Randy Lee', None), ('Samer Alanani', None)],
 ['10/02', 'off', ''],
 ['10/09',"Court 1", ('Nick Waring', None), ('Samer Alanani', None)],
 ['10/09',"Court 2", ('Jason Klein', None), ('Randy Lee', None)],
 ['10/09',"Court 3", ('Jason Visner', None), ('Nhan Vu', None)],
 ['10/09', 'off', ''],
 ['10/16',"Court 1", ('Jason Visner', None), ('Randy Lee', None)],
 ['10/16',"Court 2", ('Jason Klein', None), ('Nick Waring', None)],
 ['10/16',"Court 3", ('Nhan Vu', None), ('Samer Alanani', None)],
 ['10/23',"Court 1", ('Jason Visner', None), ('Nhan Vu', None)],
 ['10/23',"Court 2", ('Nick Waring', None), ('Samer Alanani', None)],
 ['10/23',"Court 3", ('Jason Klein', None), ('Randy Lee', None)],
 ['10/23', 'off', ''],
 ['10/30',"Court 1", ('Jason Visner', None), ('Samer Alanani', None)],
 ['10/30',"Court 2", ('Nick Waring', None), ('Randy Lee', None)],
 ['10/30', 'off', 'Jason Klein, Nhan Vu'],
 ['11/06',"Court 1", ('Nhan Vu', None), ('Randy Lee', None)],
 ['11/06',"Court 2", ('Jason Klein', None), ('Samer Alanani', None)],
 ['11/06', 'off', 'Jason Visner, Nick Waring'],
 ['11/13',"Court 1", ('Nhan Vu', None), ('Nick Waring', None)],
 ['11/13',"Court 2", ('Jason Visner', None), ('Randy Lee', None)],
 ['11/13',"Court 3", ('Jason Klein', None), ('Samer Alanani', None)],
 ['11/13', 'off', ''],
 ['11/20',"Court 1", ('Nhan Vu', None), ('Samer Alanani', None)],
 ['11/20',"Court 2", ('Nick Waring', None), ('Randy Lee', None)],
 ['11/20',"Court 3", ('Jason Klein', None), ('Jason Visner', None)],
 ['11/20', 'off', ''],
 ['12/04',"Court 1", ('Jason Klein', None), ('Nhan Vu', None)],
 ['12/04',"Court 2", ('Jason Visner', None), ('Nick Waring', None)],
 ['12/04', 'off', 'Randy Lee, Samer Alanani'],
 ['12/11',"Court 1", ('Nhan Vu', None), ('Samer Alanani', None)],
 ['12/11',"Court 2", ('Jason Klein', None), ('Nick Waring', None)],
 ['12/11',"Court 3", ('Jason Visner', None), ('Randy Lee', None)],
 ['12/11', 'off', '']]
