{'01/05': {'6pm Court 6': [['Alan', 'Bill', 'Dan', 'Mario']],
           '7:30pm Court 6': [['Kumar', 'Jacek', 'Sam', 'Amit']],
           'off': ['Jason'],
           'requested_off': []},
 '01/12': {'6pm Court 6': [['', '', '', '']],
           '7:30pm Court 6': [['', '', '', '']],
           'off': [],
           'requested_off': ["Alan"]},
 '01/19': {'6pm Court 6': [['', '', '', '']],
           '7:30pm Court 6': [['', '', '', '']],
           'off': [],
           'requested_off': ["Alan", "Jacek"]},
 '01/26': {'6pm Court 6': [['', '', '', '']],
           '7:30pm Court 6': [['', '', '', '']],
           'off': [],
           'requested_off': []},
 '02/02': {'6pm Court 6': [['', '', '', '']],
           '7:30pm Court 6': [['', '', '', '']],
           'off': [],
           'requested_off': []},
 '02/09': {'6pm Court 6': [['', '', '', '']],
           '7:30pm Court 6': [['', '', '', '']],
           'off': [],
           'requested_off': ["Kumar"]},
 '02/16': {'6pm Court 6': [['', '', '', '']],
           '7:30pm Court 6': [['', '', '', '']],
           'off': [],
           'requested_off': []},
 '02/23': {'6pm Court 6': [['', '', '', '']],
           '7:30pm Court 6': [['', '', '', '']],
           'off': [],
           'requested_off': []},
 '03/02': {'6pm Court 6': [['', '', '', '']],
           '7:30pm Court 6': [['', '', '', '']],
           'off': [],
           'requested_off': ["Bill"]},
 '03/09': {'6pm Court 6': [['', '', '', '']],
           '7:30pm Court 6': [['', '', '', '']],
           'off': [],
           'requested_off': ["Jacek"]},
 '03/16': {'6pm Court 6': [['', '', '', '']],
           '7:30pm Court 6': [['', '', '', '']],
           'off': [],
           'requested_off': ["Kumar"]},
 '03/23': {'6pm Court 6': [['', '', '', '']],
           '7:30pm Court 6': [['', '', '', '']],
           'off': [],
           'requested_off': ["Jacek"]},
 '04/06': {'6pm Court 6': [['', '', '', '']],
           '7:30pm Court 6': [['', '', '', '']],
           'off': [],
           'requested_off': []},
 '04/13': {'6pm Court 6': [['', '', '', '']],
           '7:30pm Court 6': [['', '', '', '']],
           'off': [],
           'requested_off': ["Jacek"]},
 '04/20': {'6pm Court 6': [['', '', '', '']],
           '7:30pm Court 6': [['', '', '', '']],
           'off': [],
           'requested_off': []},
}
