{'01/05': {'6pm Court 6': [['Alan', 'Bill', 'Dan', 'Mario']],
           '7:30pm Court 6': [['Amit', 'Jacek', 'Kumar', 'Sam']],
           'off': ['Jason', 'Sub'],
           'requested_off': []},
 '01/12': {'6pm Court 6': [['Bill', 'Dan', 'Jacek', 'Kumar']],
           '7:30pm Court 6': [['Amit', 'Jason', 'Mario', 'Sam']],
           'off': ['Alan', 'Sub'],
           'requested_off': ['Alan']},
 '01/19': {'6pm Court 6': [['Bill', 'Dan', 'Kumar', 'Mario']],
           '7:30pm Court 6': [['Amit', 'Jason', 'Sam', 'Sub']],
           'off': ['Alan', 'Jacek'],
           'requested_off': ['Alan', 'Jacek']},
 '01/26': {'6pm Court 6': [['Amit', 'Dan', 'Jacek', 'Kumar']],
           '7:30pm Court 6': [['Alan', 'Bill', 'Jason', 'Sam']],
           'off': ['Mario', 'Sub'],
           'requested_off': []},
 '02/02': {'6pm Court 6': [['Alan', 'Jacek', 'Kumar', 'Mario']],
           '7:30pm Court 6': [['Bill', 'Dan', 'Jason', 'Sam']],
           'off': ['Amit', 'Sub'],
           'requested_off': []},
 '02/09': {'6pm Court 6': [['Alan', 'Bill', 'Jacek', 'Mario']],
           '7:30pm Court 6': [['Amit', 'Dan', 'Jason', 'Sam']],
           'off': ['Kumar', 'Sub'],
           'requested_off': ['Kumar']},
 '02/16': {'6pm Court 6': [['Alan', 'Jacek', 'Kumar', 'Mario']],
           '7:30pm Court 6': [['Amit', 'Bill', 'Dan', 'Jason']],
           'off': ['Sam', 'Sub'],
           'requested_off': []},
 '02/23': {'6pm Court 6': [['Amit', 'Jacek', 'Kumar', 'Mario']],
           '7:30pm Court 6': [['Alan', 'Bill', 'Jason', 'Sam']],
           'off': ['Dan', 'Sub'],
           'requested_off': []},
 '03/02': {'6pm Court 6': [['Alan', 'Jacek', 'Kumar', 'Sam']],
           '7:30pm Court 6': [['Amit', 'Dan', 'Jason', 'Mario']],
           'off': ['Sub', 'Bill'],
           'requested_off': ['Bill']},
 '03/09': {'6pm Court 6': [['Alan', 'Amit', 'Bill', 'Dan']],
           '7:30pm Court 6': [['Jason', 'Kumar', 'Mario', 'Sam']],
           'off': ['Jacek', 'Sub'],
           'requested_off': ['Jacek']},
 '03/16': {'6pm Court 6': [['Bill', 'Dan', 'Jacek', 'Mario']],
           '7:30pm Court 6': [['Alan', 'Amit', 'Jason', 'Sam']],
           'off': ['Kumar', 'Sub'],
           'requested_off': ['Kumar']},
 '03/23': {'6pm Court 6': [['Alan', 'Dan', 'Kumar', 'Mario']],
           '7:30pm Court 6': [['Amit', 'Bill', 'Jason', 'Sam']],
           'off': ['Jacek', 'Sub'],
           'requested_off': ['Jacek']},
 '04/06': {'6pm Court 6': [['Alan', 'Bill', 'Dan', 'Kumar']],
           '7:30pm Court 6': [['Amit', 'Jacek', 'Mario', 'Sam']],
           'off': ['Jason', 'Sub'],
           'requested_off': []},
 '04/13': {'6pm Court 6': [['Alan', 'Bill', 'Jason', 'Kumar']],
           '7:30pm Court 6': [['Amit', 'Dan', 'Mario', 'Sam']],
           'off': ['Jacek', 'Sub'],
           'requested_off': ['Jacek']},
 '04/20': {'6pm Court 6': [['Alan', 'Bill', 'Kumar', 'Sam']],
           '7:30pm Court 6': [['Amit', 'Dan', 'Jacek', 'Jason']],
           'off': ['Mario', 'Sub'],
           'requested_off': []}}
