{'09/22': {'Court 4': [['Dave', 'Tim', 'Randy', 'Dan']],
           'Court 5': [['Sean', 'Tony', 'Jawaad', 'Jeff']],
           'off': ['Feridoon'],
           'requested_off': ['Feridoon']},
 '09/29': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': ['Tim']},
 '10/06': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': []},
 '10/13': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': []},
 '10/20': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': []},
 '10/27': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': []},
 '11/03': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': []},
 '11/10': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': []},
 '11/17': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': []},
 '11/24': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': []},
 '12/01': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': []},
 '12/08': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': []},
 '12/15': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': []}}
