{'09/22': {'Court 4': [['Dan G', 'Dave', 'Randy', 'Tim']],
           'Court 5': [['Jawaad', 'Jeff', 'Sean', 'Tony']],
           'off': ['Feridoon'],
           'requested_off': ['Feridoon']},
 '09/29': {'Court 4': [['Feridoon', 'Jawaad', 'Jeff', 'Tony']],
           'Court 5': [['Dan G', 'Dave', 'Randy', 'Sean']],
           'off': ['Tim'],
           'requested_off': ['Tim']},
 '10/06': {'Court 4': [['Feridoon', 'Jawaad', 'Tim', 'Tony']],
           'Court 5': [['Dan G', 'Jeff', 'Randy', 'Sean']],
           'off': ['Dave'],
           'requested_off': []},
 '10/13': {'Court 4': [['Dan G', 'Dave', 'Feridoon', 'Tim']],
           'Court 5': [['Jawaad', 'Jeff', 'Randy', 'Sean']],
           'off': ['Tony'],
           'requested_off': []},
 '10/20': {'Court 4': [['Dave', 'Feridoon', 'Tim', 'Tony']],
           'Court 5': [['Dan G', 'Jawaad', 'Jeff', 'Randy']],
           'off': ['Sean'],
           'requested_off': []},
 '10/27': {'Court 4': [['Feridoon', 'Sean', 'Tim', 'Tony']],
           'Court 5': [['Dan G', 'Dave', 'Jawaad', 'Randy']],
           'off': ['Jeff'],
           'requested_off': []},
 '11/03': {'Court 4': [['Feridoon', 'Jawaad', 'Jeff', 'Tony']],
           'Court 5': [['Dan G', 'Dave', 'Sean', 'Tim']],
           'off': ['Randy'],
           'requested_off': []},
 '11/10': {'Court 4': [['Dave', 'Jeff', 'Randy', 'Tim']],
           'Court 5': [['Dan G', 'Jawaad', 'Sean', 'Tony']],
           'off': ['Feridoon'],
           'requested_off': ['Feridoon']},
 '11/17': {'Court 4': [['Dave', 'Jeff', 'Randy', 'Tim']],
           'Court 5': [['Dan G', 'Jawaad', 'Sean', 'Tony']],
           'off': ['Feridoon'],
           'requested_off': ['Feridoon']},
 '11/24': {'Court 4': [['Dave', 'Jeff', 'Tim', 'Tony']],
           'Court 5': [['Dan G', 'Jawaad', 'Randy', 'Sean']],
           'off': ['Feridoon'],
           'requested_off': ['Feridoon']},
 '12/01': {'Court 4': [['Jawaad', 'Randy', 'Sean', 'Tim']],
           'Court 5': [['Dan G', 'Dave', 'Jeff', 'Tony']],
           'off': ['Feridoon'],
           'requested_off': ['Feridoon']},
 '12/08': {'Court 4': [['Dave', 'Randy', 'Tim', 'Tony']],
           'Court 5': [['Dan G', 'Jawaad', 'Jeff', 'Sean']],
           'off': ['Feridoon'],
           'requested_off': ['Feridoon']},
 '12/15': {'Court 4': [['Dan G', 'Feridoon', 'Randy', 'Tim']],
           'Court 5': [['Dave', 'Jeff', 'Sean', 'Tony']],
           'off': ['Jawaad'],
           'requested_off': []}}
