{'09/24': {'Court 4': [['Betsy', 'James'], [None, None, True]],
           'Court 5': [['Bejoy', 'Matt'], [None, None, True]],
           'Court 6': [['Rob', 'David'], [None, None, True]],
           'off': ['Eric'],
           'requested_off': ['Eric']},
 '10/01': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '10/08': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '10/15': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '10/22': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '10/29': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '11/05': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '11/12': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '11/19': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '11/26': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '12/03': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '12/10': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '12/17': {'Court 4': [['', ''], [None, None, True]],
           'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []}}
