{'09/24': {'Court 4': [['Betsy', 'James'], [1, 10, False]],
           'Court 5': [['Bejoy', 'Matt'], [9, 1, False]],
           'Court 6': [['David', 'Rob'], [9, 2, False]],
           'off': ['Eric'],
           'requested_off': ['Eric']},
 '10/01': {'Court 4': [['Eric', 'James'], [2, 9, False]],
           'Court 5': [['Bejoy', 'David'], [None, None, True]],
           'Court 6': [['Betsy', 'Matt'], [1, 9, False]],
           'off': ['Rob'],
           'requested_off': []},
 '10/08': {'Court 4': [['Bejoy', 'Eric'], [9, 0, False]],
           'Court 5': [['Betsy', 'Rob'], [5, 9, False]],
           'Court 6': [['David', 'Matt'], [7, 3, False]],
           'off': ['James'],
           'requested_off': []},
 '10/15': {'Court 4': [['James', 'Matt'], [4, 4, False]],
           'Court 5': [['Betsy', 'Eric'], [4, 9, False]],
           'Court 6': [['Bejoy', 'David'], [2, 9, False]],
           'off': ['Rob'],
           'requested_off': []},
 '10/22': {'Court 4': [['Eric', 'Matt'], [5, 9, False]],
           'Court 5': [['James', 'Rob'], [9, 4, False]],
           'Court 6': [['Betsy', 'David'], [1, 9, False]],
           'off': ['Bejoy'],
           'requested_off': []},
 '10/29': {'Court 4': [['Eric', 'Rob'], [7, 9, False]],
           'Court 5': [['David', 'James'], [9, 5, False]],
           'Court 6': [['Bejoy', 'Betsy'], [None, None, True]],
           'off': ['Matt'],
           'requested_off': []},
 '11/05': {'Court 4': [['James', 'Matt'], [None, None, True]],
           'Court 5': [['David', 'Eric'], [None, None, True]],
           'Court 6': [['Bejoy', 'Rob'], [9, 7, False]],
           'off': ['Betsy'],
           'requested_off': []},
 '11/12': {'Court 4': [['James', 'Rob'], [None, None, True]],
           'Court 5': [['Bejoy', 'Matt'], [None, None, True]],
           'Court 6': [['Betsy', 'David'], [None, None, True]],
           'off': ['Eric'],
           'requested_off': []},
 '11/19': {'Court 4': [['Bejoy', 'James'], [None, None, True]],
           'Court 5': [['Betsy', 'Eric'], [None, None, True]],
           'Court 6': [['Matt', 'Rob'], [None, None, True]],
           'off': ['David'],
           'requested_off': []},
 '11/26': {'Court 4': [['Eric', 'Rob'], [None, None, True]],
           'Court 5': [['Bejoy', 'Betsy'], [None, None, True]],
           'Court 6': [['David', 'James'], [None, None, True]],
           'off': ['Matt'],
           'requested_off': []},
 '12/03': {'Court 4': [['Eric', 'Matt'], [None, None, True]],
           'Court 5': [['David', 'Rob'], [None, None, True]],
           'Court 6': [['Bejoy', 'James'], [None, None, True]],
           'off': ['Betsy'],
           'requested_off': []},
 '12/10': {'Court 4': [['Matt', 'Rob'], [None, None, True]],
           'Court 5': [['Bejoy', 'Eric'], [None, None, True]],
           'Court 6': [['Betsy', 'James'], [None, None, True]],
           'off': ['David'],
           'requested_off': []},
 '12/17': {'Court 4': [['Betsy', 'Rob'], [None, None, True]],
           'Court 5': [['David', 'Matt'], [None, None, True]],
           'Court 6': [['Eric', 'James'], [None, None, True]],
           'off': ['Bejoy'],
           'requested_off': []}}
