{'09/22': {'Court 6': [['Dan D', 'Jacek', 'Kumar', 'Murali']],
           'off': ['Amit', 'Wade'],
           'requested_off': ['Wade', 'Amit']},
 '09/29': {'Court 6': [['Wade', 'Amit', 'Kumar', 'Murali']],
           'off': ['Dan D', 'Jacek'],
           'requested_off': []},
 '10/06': {'Court 6': [['Wade', 'Amit', 'Jacek', 'Dan D']],
           'off': ['Kumar', 'Murali'],
           'requested_off': []},
 '10/13': {'Court 6': [['Wade', 'Amit', 'Dan D', 'Jacek']],
           'off': ['Kumar', 'Murali'],
           'requested_off': []},
 '10/20': {'Court 6': [['Amit', 'Kumar', 'Wade', 'Murali']],
           'off': ['Dan D', 'Jacek'],
           'requested_off': []},
 '10/27': {'Court 6': [['Dan D', 'Jacek', 'Wade', 'Amit']],
           'off': ['Kumar', 'Murali'],
           'requested_off': []},
 '11/03': {'Court 6': [['Kumar', 'Murali', 'Wade', 'Jacek']],
           'off': ['Amit', 'Dan D'],
           'requested_off': []},
 '11/10': {'Court 6': [['Kumar', 'Amit', 'Murali', 'Dan D']],
           'off': ['Jacek', 'Wade'],
           'requested_off': []},
 '11/17': {'Court 6': [['Amit', 'Wade', 'Dan D', 'Murali']],
           'off': ['Jacek', 'Kumar'],
           'requested_off': []},
 '11/24': {'Court 6': [['Jacek', 'Kumar', 'Amit', 'Wade']],
           'off': ['Dan D', 'Murali'],
           'requested_off': []},
 '12/01': {'Court 6': [['Jacek', 'Dan D', 'Kumar', 'Murali']],
           'off': ['Amit', 'Wade'],
           'requested_off': []},
 '12/08': {'Court 6': [['Jacek', 'Amit', 'Kumar', 'Dan D']],
           'off': ['Murali', 'Wade'],
           'requested_off': []},
 '12/15': {'Court 6': [['Murali', 'Wade', 'Kumar', 'Dan D']],
           'off': ['Amit', 'Jacek'],
           'requested_off': []}}
