{'01/07': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '01/14': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '01/21': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '01/28': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '02/04': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '02/11': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '02/18': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': ["Tony M"]},
 '02/25': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '03/04': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '03/11': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '03/18': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '03/25': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '04/08': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '04/15': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '04/22': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
}
