{'01/07': {'Court 1': [['Jason', 'Nirav'], [None, None, True]],
           'Court 2': [['Sam', 'Tony M'], [None, None, True]],
           'off': ['Shannon'],
           'requested_off': ['Shannon']},
 '01/14': {'Court 1': [['Shannon', 'Nirav'], [None, None, True]],
           'Court 2': [['Sam', 'Jason'], [None, None, True]],
           'off': ['Tony M'],
           'requested_off': []},
 '01/21': {'Court 1': [['Tony M', 'Shannon'], [None, None, True]],
           'Court 2': [['Jason', 'Sam'], [None, None, True]],
           'off': ['Nirav'],
           'requested_off': []},
 '01/28': {'Court 1': [['Nirav', 'Tony M'], [None, None, True]],
           'Court 2': [['Shannon', 'Jason'], [None, None, True]],
           'off': ['Sam'],
           'requested_off': []},
 '02/04': {'Court 1': [['Nirav', 'Sam'], [None, None, True]],
           'Court 2': [['Shannon', 'Tony M'], [None, None, True]],
           'off': ['Jason'],
           'requested_off': []},
 '02/11': {'Court 1': [['Sam', 'Shannon'], [None, None, True]],
           'Court 2': [['Jason', 'Tony M'], [None, None, True]],
           'off': ['Nirav'],
           'requested_off': []},
 '02/18': {'Court 1': [['Nirav', 'Sam'], [None, None, True]],
           'Court 2': [['Jason', 'Shannon'], [None, None, True]],
           'off': ['Tony M'],
           'requested_off': ['Tony M']},
 '02/25': {'Court 1': [['Nirav', 'Tony M'], [None, None, True]],
           'Court 2': [['Sam', 'Shannon'], [None, None, True]],
           'off': ['Jason'],
           'requested_off': []},
 '03/04': {'Court 1': [['Nirav', 'Jason'], [None, None, True]],
           'Court 2': [['Tony M', 'Sam'], [None, None, True]],
           'off': ['Shannon'],
           'requested_off': []},
 '03/11': {'Court 1': [['Jason', 'Tony M'], [None, None, True]],
           'Court 2': [['Shannon', 'Nirav'], [None, None, True]],
           'off': ['Sam'],
           'requested_off': []},
 '03/18': {'Court 1': [['Shannon', 'Jason'], [None, None, True]],
           'Court 2': [['Nirav', 'Sam'], [None, None, True]],
           'off': ['Tony M'],
           'requested_off': []},
 '03/25': {'Court 1': [['Tony M', 'Shannon'], [None, None, True]],
           'Court 2': [['Sam', 'Jason'], [None, None, True]],
           'off': ['Nirav'],
           'requested_off': []},
 '04/08': {'Court 1': [['Tony M', 'Nirav'], [None, None, True]],
           'Court 2': [['Jason', 'Sam'], [None, None, True]],
           'off': ['Shannon'],
           'requested_off': []},
 '04/15': {'Court 1': [['Tony M', 'Sam'], [None, None, True]],
           'Court 2': [['Shannon', 'Nirav'], [None, None, True]],
           'off': ['Jason'],
           'requested_off': []},
 '04/22': {'Court 1': [['Nirav', 'Jason'], [None, None, True]],
           'Court 2': [['Tony M', 'Shannon'], [None, None, True]],
           'off': ['Sam'],
           'requested_off': []}}
