{'09/28': {'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '10/05': {'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '10/12': {'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '10/19': {'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '10/26': {'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '11/02': {'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '11/09': {'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '11/16': {'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '11/23': {'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '12/07': {'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '12/14': {'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '12/21': {'Court 5': [['', ''], [None, None, True]],
           'Court 6': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []}}
