{'09/24': {'Court 1': [['Don', 'Jason K'], [7, 9, False]],
           'Court 2': [['Hannah', 'Wendy'], [6, 7, False]],
           'Court 3': [['Julie', 'Nirav'], [7, 5, False]],
           'off': ['Jason V'],
           'requested_off': ['Jason V']},
 '10/01': {'Court 1': [['Jason K', 'Jason V'], [2, 9, False]],
           'Court 2': [['Don', 'Hannah'], [3, 10, False]],
           'Court 3': [['Nirav', 'Wendy'], [7, 4, False]],
           'off': ['Julie'],
           'requested_off': []},
 '10/08': {'Court 1': [['Hannah', 'Julie'], [4, 6, False]],
           'Court 2': [['Jason V', 'Nirav'], [9, 1, False]],
           'Court 3': [['Don', 'Jason K'], [8, 9, False]],
           'off': ['Wendy'],
           'requested_off': []},
 '10/15': {'Court 1': [['Jason V', 'Julie'], [9, 4, False]],
           'Court 2': [['Don', 'Wendy'], [5, 9, False]],
           'Court 3': [['Jason K', 'Nirav'], [6, 9, False]],
           'off': ['Hannah'],
           'requested_off': []},
 '10/22': {'Court 1': [['Hannah', 'Jason V'], [6, 9, False]],
           'Court 2': [['Julie', 'Wendy'], [3, 6, False]],
           'Court 3': [['Don', 'Jason K'], [None, None, True]],
           'off': ['Nirav'],
           'requested_off': ['Nirav']},
 '10/29': {'Court 1': [['Jason K', 'Julie'], [None, None, True]],
           'Court 2': [['Hannah', 'Wendy'], [6, 4, False]],
           'Court 3': [['Don', 'Nirav'], [None, None, True]],
           'off': ['Jason V'],
           'requested_off': []},
 '11/05': {'Court 1': [['Jason K', 'Wendy'], [7, 5, False]],
           'Court 2': [['Don', 'Jason V'], [None, None, True]],
           'Court 3': [['Hannah', 'Nirav'], [6, 9, False]],
           'off': ['Julie'],
           'requested_off': []},
 '11/12': {'Court 1': [['Hannah', 'Jason V'], [5, 8, False]],
           'Court 2': [['Jason K', 'Julie'], [5, 8, False]],
           'Court 3': [['Don', 'Nirav'], [None, None, True]],
           'off': ['Wendy'],
           'requested_off': []},
 '11/19': {'Court 1': [['Jason V', 'Julie'], [None, None, True]],
           'Court 2': [['Hannah', 'Jason K'], [None, None, True]],
           'Court 3': [['Nirav', 'Wendy'], [6, 5, False]],
           'off': ['Don'],
           'requested_off': []},
 '11/26': {'Court 1': [['Julie', 'Nirav'], [None, None, True]],
           'Court 2': [['Don', 'Jason V'], [None, None, True]],
           'Court 3': [['Jason K', 'Wendy'], [None, None, True]],
           'off': ['Hannah'],
           'requested_off': []},
 '12/03': {'Court 1': [['Jason V', 'Wendy'], [9, 5, False]],
           'Court 2': [['Hannah', 'Nirav'], [5, 8, False]],
           'Court 3': [['Don', 'Julie'], [None, None, True]],
           'off': ['Jason K'],
           'requested_off': []},
 '12/10': {'Court 1': [['Julie', 'Wendy'], [2, 9, False]],
           'Court 2': [['Jason K', 'Jason V'], [None, None, True]],
           'Court 3': [['Don', 'Hannah'], [None, None, True]],
           'off': ['Nirav'],
           'requested_off': []},
 '12/17': {'Court 1': [['Hannah', 'Julie'], [None, None, True]],
           'Court 2': [['Jason V', 'Nirav'], [None, None, True]],
           'Court 3': [['Don', 'Wendy'], [None, None, True]],
           'off': ['Jason K'],
           'requested_off': []}}
