{'09/24': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '10/01': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '10/08': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '10/15': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '10/22': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '10/29': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '11/05': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '11/12': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '11/19': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '11/26': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '12/03': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '12/10': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '12/17': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []}}
