{'01/13': {'7:30 Court 4': [['Dave', 'Sean', 'Tim', 'Trevor']],
           '7:30 Court 5': [['Feridoon', 'Randy', 'Tony M', 'Tony O']],
           'off': ['Jawaad', 'Jeff W', 'Vignesh'],
           'requested_off': []},
 '01/20': {'7:30 Court 4': [['Jeff W', 'Randy', 'Tony M', 'Trevor']],
           '7:30 Court 5': [['Dave', 'Jawaad', 'Sean', 'Vignesh']],
           'off': ['Feridoon', 'Tim', 'Tony O'],
           'requested_off': []},
 '01/27': {'7:30 Court 4': [['Feridoon', 'Jawaad', 'Tim', 'Vignesh']],
           '7:30 Court 5': [['Jeff W', 'Randy', 'Tony M', 'Tony O']],
           'off': ['Dave', 'Sean', 'Trevor'],
           'requested_off': []},
 '02/03': {'7:30 Court 4': [['Dave', 'Feridoon', 'Jawaad', 'Jeff W']],
           '7:30 Court 5': [['Sean', 'Tim', 'Tony M', 'Trevor']],
           'off': ['Randy', 'Tony O', 'Vignesh'],
           'requested_off': []},
 '02/10': {'7:30 Court 4': [['Feridoon', 'Jawaad', 'Sean', 'Vignesh']],
           '7:30 Court 5': [['Randy', 'Tim', 'Tony M', 'Tony O']],
           'off': ['Dave', 'Jeff W', 'Trevor'],
           'requested_off': []},
 '02/17': {'7:30 Court 4': [['Dave', 'Feridoon', 'Jawaad', 'Trevor']],
           '7:30 Court 5': [['Jeff W', 'Randy', 'Tony O', 'Vignesh']],
           'off': ['Sean', 'Tim', 'Tony M'],
           'requested_off': []},
 '02/24': {'7:30 Court 4': [['Feridoon', 'Jawaad', 'Randy', 'Trevor']],
           '7:30 Court 5': [['Dave', 'Tony M', 'Tony O', 'Vignesh']],
           'off': ['Jeff W', 'Sean', 'Tim'],
           'requested_off': []},
 '03/03': {'7:30 Court 4': [['Feridoon', 'Jeff W', 'Sean', 'Tim']],
           '7:30 Court 5': [['Randy', 'Tony O', 'Trevor', 'Vignesh']],
           'off': ['Dave', 'Jawaad', 'Tony M'],
           'requested_off': ['Jawaad']},
 '03/10': {'7:30 Court 4': [['Dave', 'Feridoon', 'Jeff W', 'Sean']],
           '7:30 Court 5': [['Tim', 'Tony M', 'Tony O', 'Vignesh']],
           'off': ['Jawaad', 'Randy', 'Trevor'],
           'requested_off': ['Jawaad']},
 '03/17': {'7:30 Court 4': [['Dave', 'Randy', 'Tim', 'Tony M']],
           '7:30 Court 5': [['Feridoon', 'Jeff W', 'Sean', 'Trevor']],
           'off': ['Jawaad', 'Tony O', 'Vignesh'],
           'requested_off': ['Jawaad']},
 '03/31': {'7:30 Court 4': [['Dave', 'Jawaad', 'Tim', 'Tony O']],
           '7:30 Court 5': [['Feridoon', 'Tony M', 'Trevor', 'Vignesh']],
           'off': ['Jeff W', 'Randy', 'Sean'],
           'requested_off': []},
 '04/07': {'7:30 Court 4': [['Jawaad', 'Jeff W', 'Randy', 'Sean']],
           '7:30 Court 5': [['Feridoon', 'Tim', 'Tony O', 'Vignesh']],
           'off': ['Dave', 'Tony M', 'Trevor'],
           'requested_off': []},
 '04/14': {'7:30 Court 4': [['Dave', 'Randy', 'Sean', 'Trevor']],
           '7:30 Court 5': [['Jawaad', 'Jeff W', 'Tony M', 'Vignesh']],
           'off': ['Feridoon', 'Tim', 'Tony O'],
           'requested_off': ['Feridoon']},
 '04/21': {'7:30 Court 4': [['Jawaad', 'Tim', 'Tony M', 'Trevor']],
           '7:30 Court 5': [['Dave', 'Jeff W', 'Sean', 'Tony O']],
           'off': ['Feridoon', 'Randy', 'Vignesh'],
           'requested_off': ['Feridoon']},
 '04/28': {'7:30 Court 4': [['Jawaad', 'Jeff W', 'Randy', 'Trevor']],
           '7:30 Court 5': [['Sean', 'Tim', 'Tony M', 'Vignesh']],
           'off': ['Dave', 'Feridoon', 'Tony O'],
           'requested_off': ['Feridoon']},
 '05/05': {'7:30 Court 4': [['Feridoon', 'Jawaad', 'Randy', 'Tony O']],
           '7:30 Court 5': [['Dave', 'Tim', 'Trevor', 'Vignesh']],
           'off': ['Jeff W', 'Sean', 'Tony M'],
           'requested_off': []}}
