{'01/15': {'Court 1': [['Hiroki', 'Jason V'], [4, 9, False]],
           'Court 2': [['Arthur', 'Ramsey'], [3, 6, False]],
           'Court 3': [['Nirav', 'Samer'], [9, 6, False]],
           'off': ['Betsy', 'Brady', 'Jason K'],
           'requested_off': ['Betsy']},
 '01/22': {'Court 1': [['Betsy', 'Brady'], [9, 3, False]],
           'Court 2': [['Jason K', 'Jason V'], [4, 9, False]],
           'Court 3': [['Hiroki', 'Ramsey'], [8, 3, False]],
           'off': ['Arthur', 'Nirav', 'Samer'],
           'requested_off': ['Samer']},
 '01/29': {'Court 1': [['Jason K', 'Samer'], [9, 3, False]],
           'Court 2': [['Arthur', 'Brady'], [2, 13, False]],
           'Court 3': [['Betsy', 'Nirav'], [6, 0, False]],
           'off': ['Hiroki', 'Jason V', 'Ramsey'],
           'requested_off': ['Ramsey']},
 '02/05': {'Court 1': [['Jason K', 'Nirav'], [9, 8, False]],
           'Court 2': [['Arthur', 'Betsy'], [2, 9, False]],
           'Court 3': [['Brady', 'Jason V'], [4, 9, False]],
           'off': ['Hiroki', 'Ramsey', 'Samer'],
           'requested_off': ['Ramsey']},
 '02/12': {'Court 1': [['Ramsey', 'Samer'], [5, 4, False]],
           'Court 2': [['Hiroki', 'Jason K'], [9, 4, False]],
           'Court 3': [['Betsy', 'Jason V'], [9, 4, False]],
           'off': ['Arthur', 'Brady', 'Nirav'],
           'requested_off': ['Nirav']},
 '02/19': {'Court 1': [['Brady', 'Ramsey'], [9, 4, False]],
           'Court 2': [['Arthur', 'Samer'], [5, 9, False]],
           'Court 3': [['Betsy', 'Hiroki'], [9, 2, False]],
           'off': ['Jason K', 'Jason V', 'Nirav'],
           'requested_off': ['Nirav']},
 '02/26': {'Court 1': [['Arthur', 'Nirav'], [9, 4, False]],
           'Court 2': [['Hiroki', 'Samer'], [5, 7, False]],
           'Court 3': [['Jason K', 'Ramsey'], [None, None, True]],
           'off': ['Betsy', 'Brady', 'Jason V'],
           'requested_off': []},
 '03/05': {'Court 1': [['Jason V', 'Nirav'], [9, 6, False]],
           'Court 2': [['Brady', 'Hiroki'], [3, 7, False]],
           'Court 3': [['Arthur', 'Jason K'], [4, 9, False]],
           'off': ['Betsy', 'Ramsey', 'Samer'],
           'requested_off': []},
 '03/12': {'Court 1': [['Betsy', 'Jason K'], [9, 1, False]],
           'Court 2': [['Hiroki', 'Nirav'], [5, 6, False]],
           'Court 3': [['Arthur', 'Jason V'], [4, 9, False]],
           'off': ['Brady', 'Ramsey', 'Samer'],
           'requested_off': []},
 '03/19': {'Court 1': [['Jason V', 'Ramsey'], [None, None, True]],
           'Court 2': [['Brady', 'Jason K'], [9, 7, False]],
           'Court 3': [['Betsy', 'Samer'], [9, 2, False]],
           'off': ['Arthur', 'Hiroki', 'Nirav'],
           'requested_off': []},
 '04/02': {'Court 1': [['Arthur', 'Hiroki'], [5, 9, False]],
           'Court 2': [['Nirav', 'Ramsey'], [None, None, True]],
           'Court 3': [['Brady', 'Samer'], [9, 7, False]],
           'off': ['Betsy', 'Jason K', 'Jason V'],
           'requested_off': []},
 '04/09': {'Court 1': [['Betsy', 'Ramsey'], [None, None, True]],
           'Court 2': [['Brady', 'Nirav'], [9, 2, False]],
           'Court 3': [['Jason V', 'Samer'], [9, 4, False]],
           'off': ['Arthur', 'Hiroki', 'Jason K'],
           'requested_off': []},
 '04/16': {'Court 1': [['Nirav', 'Samer'], [9, 6, True]],
           'Court 2': [['Hiroki', 'Jason K'], [7, 5, False]],
           'Court 3': [['Betsy', 'Jason V'], [9, 2, False]],
           'off': ['Arthur', 'Brady', 'Ramsey'],
           'requested_off': ['TBD']},
 '04/23': {'Court 1': [['Brady', 'Jason K'], [9, 3, False]],
           'Court 2': [['Nirav', 'Ramsey'], [6, 5, False]],
           'Court 3': [['Arthur', 'Samer'], [9, 7, False]],
           'off': ['Betsy', 'Hiroki', 'Jason V'],
           'requested_off': ['Betsy']},
 '04/30': {'Court 1': [['Betsy', 'Hiroki'], [9, 3, True]],
           'Court 2': [['Arthur', 'Brady'], [2, 9, True]],
           'Court 3': [['Jason V', 'Ramsey'], [9, 1, True]],
           'off': ['Jason K', 'Nirav', 'Samer'],
           'requested_off': ['TBD']},
 '05/07': {'Court 1': [['Brady', 'Jason V'], [None, None, True]],
           'Court 2': [['Hiroki', 'Samer'], [None, None, True]],
           'Court 3': [['Nirav', 'Jason K'], [None, None, True]],
           'Court 4': [['Arthur', 'Ramsey'], [None, None, True]],
           'off': ['Betsy'],
           'requested_off': ['Betsy']}}
