{'01/15': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '01/22': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '01/29': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '02/05': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '02/12': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '02/19': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '02/26': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '03/05': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '03/12': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '03/19': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '04/02': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '04/09': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '04/16': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '04/23': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '04/30': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []},
 '05/07': {'Court 1': [['', ''], [None, None, True]],
           'Court 2': [['', ''], [None, None, True]],
           'Court 3': [['', ''], [None, None, True]],
           'off': [],
           'requested_off': []}}
