{'01/15': {'Court 1': [['Hiroki', 'Jason V'], [None, None, True]],
           'Court 2': [['Arthur', 'Ramzi'], [None, None, True]],
           'Court 3': [['Nirav', 'Samer'], [None, None, True]],
           'off': ['Brady', 'Jason K'],
           'requested_off': []},
 '01/22': {'Court 1': [['Brady', 'Jason K'], [None, None, True]],
           'Court 2': [['Hiroki', 'Samer'], [None, None, True]],
           'Court 3': [['Arthur', 'Jason V'], [None, None, True]],
           'off': ['Nirav', 'Ramzi'],
           'requested_off': []},
 '01/29': {'Court 1': [['Brady', 'Nirav'], [None, None, True]],
           'Court 2': [['Hiroki', 'Ramzi'], [None, None, True]],
           'Court 3': [['Jason K', 'Jason V'], [None, None, True]],
           'off': ['Arthur', 'Samer'],
           'requested_off': []},
 '02/05': {'Court 1': [['Jason K', 'Nirav'], [None, None, True]],
           'Court 2': [['Brady', 'Ramzi'], [None, None, True]],
           'Court 3': [['Arthur', 'Samer'], [None, None, True]],
           'off': ['Hiroki', 'Jason V'],
           'requested_off': []},
 '02/12': {'Court 1': [['Jason K', 'Ramzi'], [None, None, True]],
           'Court 2': [['Hiroki', 'Samer'], [None, None, True]],
           'Court 3': [['Brady', 'Jason V'], [None, None, True]],
           'off': ['Arthur', 'Nirav'],
           'requested_off': []},
 '02/19': {'Court 1': [['Arthur', 'Nirav'], [None, None, True]],
           'Court 2': [['Hiroki', 'Jason K'], [None, None, True]],
           'Court 3': [['Ramzi', 'Samer'], [None, None, True]],
           'off': ['Brady', 'Jason V'],
           'requested_off': []},
 '02/26': {'Court 1': [['Jason V', 'Nirav'], [None, None, True]],
           'Court 2': [['Arthur', 'Hiroki'], [None, None, True]],
           'Court 3': [['Brady', 'Samer'], [None, None, True]],
           'off': ['Jason K', 'Ramzi'],
           'requested_off': []},
 '03/05': {'Court 1': [['Brady', 'Jason V'], [None, None, True]],
           'Court 2': [['Nirav', 'Ramzi'], [None, None, True]],
           'Court 3': [['Arthur', 'Jason K'], [None, None, True]],
           'off': ['Hiroki', 'Samer'],
           'requested_off': []},
 '03/12': {'Court 1': [['Jason V', 'Samer'], [None, None, True]],
           'Court 2': [['Hiroki', 'Nirav'], [None, None, True]],
           'Court 3': [['Arthur', 'Brady'], [None, None, True]],
           'off': ['Jason K', 'Ramzi'],
           'requested_off': []},
 '03/19': {'Court 1': [['Arthur', 'Ramzi'], [None, None, True]],
           'Court 2': [['Jason K', 'Jason V'], [None, None, True]],
           'Court 3': [['Brady', 'Hiroki'], [None, None, True]],
           'off': ['Nirav', 'Samer'],
           'requested_off': []},
 '04/02': {'Court 1': [['Jason V', 'Samer'], [None, None, True]],
           'Court 2': [['Arthur', 'Hiroki'], [None, None, True]],
           'Court 3': [['Brady', 'Nirav'], [None, None, True]],
           'off': ['Jason K', 'Ramzi'],
           'requested_off': []},
 '04/09': {'Court 1': [['Nirav', 'Ramzi'], [None, None, True]],
           'Court 2': [['Arthur', 'Samer'], [None, None, True]],
           'Court 3': [['Brady', 'Jason K'], [None, None, True]],
           'off': ['Hiroki', 'Jason V'],
           'requested_off': []},
 '04/16': {'Court 1': [['Jason V', 'Nirav'], [None, None, True]],
           'Court 2': [['Hiroki', 'Ramzi'], [None, None, True]],
           'Court 3': [['Arthur', 'Jason K'], [None, None, True]],
           'off': ['Brady', 'Samer'],
           'requested_off': []},
 '04/23': {'Court 1': [['Jason K', 'Ramzi'], [None, None, True]],
           'Court 2': [['Hiroki', 'Nirav'], [None, None, True]],
           'Court 3': [['Brady', 'Samer'], [None, None, True]],
           'off': ['Arthur', 'Jason V'],
           'requested_off': []},
 '04/30': {'Court 1': [['Jason K', 'Nirav'], [None, None, True]],
           'Court 2': [['Arthur', 'Jason V'], [None, None, True]],
           'Court 3': [['Ramzi', 'Samer'], [None, None, True]],
           'off': ['Brady', 'Hiroki'],
           'requested_off': []},
 '05/07': {'Court 1': [['Jason K', 'Samer'], [None, None, True]],
           'Court 2': [['Jason V', 'Ramzi'], [None, None, True]],
           'Court 3': [['Brady', 'Hiroki'], [None, None, True]],
           'off': ['Arthur', 'Nirav'],
           'requested_off': []}}
