{'09/28': {'Court 5': [['Judith', 'Katie', 'Mary Ellen', 'Stacy']],
           'Court 6': [['Karen', 'Lisa', 'Mary Lynn', 'Sheila']],
           'off': ['Christina', 'Jill'],
           'requested_off': ['Christina', 'Jill']},
 '10/05': {'Court 5': [['Christina', 'Judith', 'Sheila', 'Stacy']],
           'Court 6': [['Jill', 'Katie', 'Mary Ellen', 'Mary Lynn']],
           'off': ['Karen', 'Lisa'],
           'requested_off': ['Karen']},
 '10/12': {'Court 5': [['Jill', 'Judith', 'Karen', 'Lisa']],
           'Court 6': [['Mary Ellen', 'Mary Lynn', 'Sheila', 'Stacy']],
           'off': ['Christina', 'Katie'],
           'requested_off': ['Christina']},
 '10/19': {'Court 5': [['Christina', 'Jill', 'Katie', 'Lisa']],
           'Court 6': [['Judith', 'Mary Ellen', 'Mary Lynn', 'Sheila']],
           'off': ['Karen', 'Stacy'],
           'requested_off': ['Karen', 'Stacy']},
 '10/26': {'Court 5': [['Christina', 'Jill', 'Katie', 'Sheila']],
           'Court 6': [['Karen', 'Lisa', 'Mary Ellen', 'Stacy']],
           'off': ['Judith', 'Mary Lynn'],
           'requested_off': []},
 '11/02': {'Court 5': [['Christina', 'Jill', 'Karen', 'Mary Lynn']],
           'Court 6': [['Judith', 'Katie', 'Lisa', 'Stacy']],
           'off': ['Mary Ellen', 'Sheila'],
           'requested_off': []},
 '11/09': {'Court 5': [['Jill', 'Karen', 'Katie', 'Stacy']],
           'Court 6': [['Judith', 'Lisa', 'Mary Ellen', 'Sheila']],
           'off': ['Christina', 'Mary Lynn'],
           'requested_off': ['Christina']},
 '11/16': {'Court 5': [['Christina', 'Karen', 'Lisa', 'Mary Ellen']],
           'Court 6': [['Judith', 'Katie', 'Mary Lynn', 'Stacy']],
           'off': ['Jill', 'Sheila'],
           'requested_off': ['Jill']},
 '11/23': {'Court 5': [['Jill', 'Karen', 'Mary Lynn', 'Sheila']],
           'Court 6': [['Christina', 'Judith', 'Katie', 'Mary Ellen']],
           'off': ['Lisa', 'Stacy'],
           'requested_off': ['Stacy']},
 '12/07': {'Court 5': [['Jill', 'Katie', 'Mary Ellen', 'Sheila']],
           'Court 6': [['Karen', 'Lisa', 'Mary Lynn', 'Stacy']],
           'off': ['Christina', 'Judith'],
           'requested_off': ['Christina']},
 '12/14': {'Court 5': [['Jill', 'Judith', 'Karen', 'Lisa']],
           'Court 6': [['Christina', 'Mary Lynn', 'Sheila', 'Stacy']],
           'off': ['Katie', 'Mary Ellen'],
           'requested_off': []},
 '12/21': {'Court 5': [['Christina', 'Karen', 'Katie', 'Stacy']],
           'Court 6': [['Jill', 'Lisa', 'Mary Lynn', 'Sheila']],
           'off': ['Judith', 'Mary Ellen'],
           'requested_off': []}}
