{'09/28': {'Court 5': [['Judy', 'Stacy', 'Katie', 'Mary Ellen']],
           'Court 6': [['Mary Lynn', 'Lisa', 'Sheila', 'Karen']],
           'off': ['Christina', 'Jill'],
           'requested_off': ['Christina', 'Jill']},
 '10/05': {'Court 5': [['', '', '', '']],
           'Court 6': [['', '', '', '']],
           'off': [],
           'requested_off': ['Karen']},
 '10/12': {'Court 5': [['', '', '', '']],
           'Court 6': [['', '', '', '']],
           'off': [],
           'requested_off': ['Christina']},
 '10/19': {'Court 5': [['', '', '', '']],
           'Court 6': [['', '', '', '']],
           'off': [],
           'requested_off': ['Karen']},
 '10/26': {'Court 5': [['', '', '', '']],
           'Court 6': [['', '', '', '']],
           'off': [],
           'requested_off': []},
 '11/02': {'Court 5': [['', '', '', '']],
           'Court 6': [['', '', '', '']],
           'off': [],
           'requested_off': []},
 '11/09': {'Court 5': [['', '', '', '']],
           'Court 6': [['', '', '', '']],
           'off': [],
           'requested_off': ['Christina']},
 '11/16': {'Court 5': [['', '', '', '']],
           'Court 6': [['', '', '', '']],
           'off': [],
           'requested_off': ['Jill']},
 '11/23': {'Court 5': [['', '', '', '']],
           'Court 6': [['', '', '', '']],
           'off': [],
           'requested_off': ['Stacy']},
 '12/07': {'Court 5': [['', '', '', '']],
           'Court 6': [['', '', '', '']],
           'off': [],
           'requested_off': ['Christina']},
 '12/14': {'Court 5': [['', '', '', '']],
           'Court 6': [['', '', '', '']],
           'off': [],
           'requested_off': []},
 '12/21': {'Court 5': [['', '', '', '']],
           'Court 6': [['', '', '', '']],
           'off': [],
           'requested_off': []}}
