{'01/05': {'Court 4': [['Dave', 'Randy', 'Sean', 'Tim']],
           'Court 5': [['Feridoon', 'Jawaad', 'Tony M', 'Tony O']],
           'off': ['Jeff', 'Sub'],
           'requested_off': ['Jeff']},
 '01/12': {'Court 4': [['Jawaad', 'Jeff', 'Tim', 'Tony O']],
           'Court 5': [['Dave', 'Randy', 'Sean', 'Tony M']],
           'off': ['Feridoon', 'Sub'],
           'requested_off': ['Feridoon']},
 '01/19': {'Court 4': [['Jawaad', 'Jeff', 'Randy', 'Tony M']],
           'Court 5': [['Sub', 'Sean', 'Tim', 'Tony O']],
           'off': ['Feridoon', 'Dave'],
           'requested_off': ['Feridoon']},
 '01/26': {'Court 4': [['Feridoon', 'Jawaad', 'Randy', 'Tony M']],
           'Court 5': [['Sub', 'Sean', 'Tim', 'Tony O']],
           'off': ['Jeff', 'Dave'],
           'requested_off': ['Jeff']},
 '02/02': {'Court 4': [['Feridoon', 'Jawaad', 'Jeff', 'Randy']],
           'Court 5': [['Sean', 'Tim', 'Tony M', 'Tony O']],
           'off': ['Dave', 'Sub'],
           'requested_off': []},
 '02/09': {'Court 4': [['Sub', 'Feridoon', 'Jawaad', 'Sean']],
           'Court 5': [['Jeff', 'Randy', 'Tony M', 'Tony O']],
           'off': ['Dave', 'Tim'],
           'requested_off': ['Tim']},
 '02/16': {'Court 4': [['Sub', 'Feridoon', 'Jawaad', 'Jeff']],
           'Court 5': [['Randy', 'Sean', 'Tim', 'Tony O']],
           'off': ['Dave', 'Tony M'],
           'requested_off': ['Tony M']},
 '02/23': {'Court 4': [['Feridoon', 'Jeff', 'Tim', 'Tony M']],
           'Court 5': [['Sub', 'Randy', 'Sub', 'Tony O']],
           'off': ['Dave', 'Jawaad', 'Sean'],
           'requested_off': ['Sean', 'Jawaad']},
 '03/02': {'Court 4': [['Feridoon', 'Jeff', 'Sean', 'Tim']],
           'Court 5': [['Sub', 'Randy', 'Tony M', 'Tony O']],
           'off': ['Jawaad', 'Dave'],
           'requested_off': ['Jawaad']},
 '03/09': {'Court 4': [['Sub', 'Feridoon', 'Sean', 'Tim']],
           'Court 5': [['Jeff', 'Randy', 'Tony M', 'Tony O']],
           'off': ['Jawaad', 'Dave'],
           'requested_off': ['Jawaad']},
 '03/16': {'Court 4': [['Feridoon', 'Sean', 'Tim', 'Tony M']],
           'Court 5': [['Sub', 'Randy', 'Sub', 'Tony O']],
           'off': ['Dave', 'Jawaad', 'Jeff'],
           'requested_off': ['Jeff', 'Jawaad']},
 '03/23': {'Court 4': [['Feridoon', 'Jawaad', 'Jeff', 'Tim']],
           'Court 5': [['Randy', 'Sean', 'Tony M', 'Tony O']],
           'off': ['Dave', 'Sub'],
           'requested_off': []},
 '04/06': {'Court 4': [['Feridoon', 'Jawaad', 'Jeff', 'Sean']],
           'Court 5': [['Tony O', 'Randy', 'Tim', 'Tony M']],
           'off': ['Sub', 'Dave'],
           'requested_off': []},
 '04/13': {'Court 4': [['Feridoon', 'Jawaad', 'Tim', 'Tony M']],
           'Court 5': [['Randy', 'Jeff', 'Sean', 'Tony O']],
           'off': ['Dave', 'Sub'],
           'requested_off': []},
 '04/20': {'Court 4': [['Tony O', 'Feridoon', 'Jawaad', 'Tony M']],
           'Court 5': [['Jeff', 'Randy', 'Sean', 'Tim']],
           'off': ['Sub', 'Dave'],
           'requested_off': []}}
