{'01/05': {'Court 4': [['Tim', 'Dave', 'Randy', 'Sean']],
           'Court 5': [['Feridoon', 'Tony O', 'Tony M', 'Jawaad']],
           'off': ["Jeff"],
           'requested_off': ["Jeff"]},
 '01/12': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': ["Feridoon"]},
 '01/19': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': ["Feridoon"]},
 '01/26': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': ["Jeff"]},
 '02/02': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': []},
 '02/09': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': ["Tim"]},
 '02/16': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': ["Tony M"]},
 '02/23': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': ["Sean", "Jawaad"]},
 '03/02': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': ["Jawaad"]},
 '03/09': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': ["Jawaad"]},
 '03/16': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': ["Jeff", "Jawaad"]},
 '03/23': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': []},
 '04/06': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': []},
 '04/13': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': []},
 '04/20': {'Court 4': [['', '', '', '']],
           'Court 5': [['', '', '', '']],
           'off': [],
           'requested_off': []}}
